run:
  timeout: 15m
  config: ./.golangci.yml
  new: true
  color: always
  build-tags:
    - integration
    - test
    - tools

# TODO_TECHDEBT: Enable each linter listed, 1 by 1, fixing issues as they appear.
linters:
  enable:
    # - govet
    # - errcheck
    # - unused
    - revive
    - gofumpt
    - lll
    - gci

linters-settings:
  govet:
    check-shadowing: true
  lll:
    line-length: 120
    tab-width: 4
  gci:
    sections:
      - standard # std lib
      - default # external
      - prefix(github.com/pokt-network/poktroll) # local imports
    skip-generated: true
    custom-order: true
  skip-files:
    - "*.pb.go"
    - "*/vendor/*"

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
  # TODO_CONSIDERATION/TODO_TECHDEBT: Perhaps we should prefer enforcing the best
  # practices suggested by the linters over convention or the default in generated
  # code (where possible). The more exceptions we have, the bigger the gaps will be
  # in our linting coverage. We could eliminate or reduce these exceptions step-
  # by-step.
  exclude-rules:
    # Exclude cosmos-sdk module genesis.go files as they are generated with an
    # empty import block containing a comment used by ignite CLI.
    - path: ^x/.+/genesis\.go$
      linters:
        - gci
    # Exclude cosmos-sdk module module.go files as they are generated with unused
    # parameters and unchecked errors.
    - path: ^x/.+/module\.go$
      linters:
        - lll
        - gci
        - revive
        - errcheck
    # Exclude cosmos-sdk module tx.go files as they are generated with unused
    # constants.
    - path: ^x/.+/cli/tx\.go$
      linters:
        - gci
        - lll
        - unused
    # Exclude simulation code as it's generated with lots of unused parameters.
    - path: .*/simulation/.*|_simulation\.go$
      linters:
        - gci
        - lll
        - revive
    # Exclude cosmos-sdk module codec files as they are scaffolded with a unused
    # parameters and a comment used by ignite CLI.
    - path: ^x/.+/codec.go$
      linters:
        - lll
        - gci
        - revive
    - path: _test\.go$
      linters:
        - errcheck
    # Exclude line length check for errors.go files as they are easier to read
    # as as single line.
    - path: errors\.go$
      linters:
        - lll
    # Exclude app module code as it's generated with lots with long lines and
    # improperly formatted imports.
    - path: ^app
      linters:
        - lll
        - gci
    # Exclude cmd directory code as it's generated with lots with long lines and
    # improperly formatted imports.
    - path: ^cmd/poc
      linters:
        - lll
        - gci
  new: true
  # TODO_IMPROVE: see https://golangci-lint.run/usage/configuration/#issues-configuration
  #fix: true,
