query_node_rpc_url: tcp://poktroll-validator1:36657
query_node_grpc_url: tcp://poktroll-validator1:36658
signing_key: app1
self_signing: true
listening_endpoint: http://localhost:42069
metrics:
  enabled: true
  addr: :9090
