# Whether the server should sign all incoming requests with its own ring (for applications)
self_signing: true
# The name of the key (in the keyring) that will be used to sign relays
signing_key: app1
# The host and port that the appgate server will listen on
listening_endpoint: http://localhost:42069
# tcp://<host>:<port> to a full pocket node for reading data
query_node_grpc_url: tcp://127.0.0.1:36658
# grpc client insecure flag
grpc_insecure: true
# tcp://<host>:<port> to a full pocket node websocket endpoint for listening for on-chain events
pocket_node_websocket_url: tcp://127.0.0.1:36657
