# TODO(@Olshansk, @okdas): Add more services (in addition to anvil) for apps and suppliers to stake for.
# TODO_TECHDEBT: svc1 below are only in place to make GetSession testable
stake_amount: 1000upokt
services:
  - service_id: etherium
    endpoints:
      # The endpoint URL for the Anvil service is provided via the RelayMiner.
      # The RelayMiner acts as a proxy, forwarding requests to the actual Anvil data node behind it.
      # This setup allows for flexible and dynamic service provisioning within the network.
      - url: http://bhs.kdas.me:8545
        rpc_type: json_rpc
