name: Run tests

on:
  push:
    branches: ["main"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  GKE_CLUSTER: protocol-us-central1
  GKE_ZONE: us-central1

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: install ignite
        # TODO_TECHDEBT: upgrade to the latest Ignite (the latest at the moment of creating a note is 0.28). Need to downgrade to fix CI pipelines. Might be done in scope of #240.
        run: |
          # curl https://get.ignite.com/cli! | bash
          wget https://github.com/ignite/cli/releases/download/v0.27.2/ignite_0.27.2_linux_amd64.tar.gz
          tar -xzf ignite_0.27.2_linux_amd64.tar.gz
          sudo mv ignite /usr/local/bin/ignite
          ignite version

      - uses: actions/checkout@v3
        with:
          fetch-depth: "0" # Per https://github.com/ignite/cli/issues/1674#issuecomment-1144619147

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.10"

      - name: Install CI dependencies
        run: make install_ci_deps

      - name: Generate protobufs
        run: make proto_regen

      - name: Generate mocks
        run: make go_mockgen

      - name: Fix imports
        run: make gci

      - name: Format the repo
        run: make gofumpt

      # Fetch a list of all modified files in this PR.
      - name: Get Modified Files
        run: git diff --name-only ${{ github.event.before }} ${{ github.sha }} > modified_files.txt

      # Filter the list of files modified in this PR to exclude those that have
      # ignite scaffold comments in their import block, this is because gci
      # (golangci-lint's import formatter) doesn't support this kind of filtering
      # and removes all comments from import blocks.
      - name: Filter For Lintable Files
        run: go run ./tools/scripts/scaffold_filter/main.go $(cat modified_files.txt) > files_to_lint.txt

      # Run golangci-lint on the filtered files from this PR - allowing gci to
      # catch any improperly formatted import blocks in this PR.
      - name: Run golangci-lint (filtered for scaffold comments)
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=15m --config=.golangci.yml $(cat files_to_lint.txt)
          only-new-issues: true
          skip-cache: true

      # Generate a list of files that were excluded from linting in the last
      # golangci-lint step.
      - name: Generate List of Excluded Files
        run: |
          comm -23 <(sort modified_files.txt) <(sort files_to_lint.txt) > excluded_files.txt

      # Do a second lint pass without import checking (after filtered lint) to
      # catcy any linter errors in files that were excluded in the first pass.
      # This step disables gci checks, to check for all other linter errors,
      # on every file in the PR, without filtering.
      - name: Run golangci-lint (without import checking)
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=15m --config=.golangci.yml --disable gci $(cat excluded_files.txt)
          only-new-issues: true
          skip-cache: true

      - name: Test
        run: make go_test
